---
- hosts: lxd
  become: yes
  gather_facts: yes

  tasks:
    - name: Install epel-release and ansible in rpm based systems
      yum: name={{ item }} state=latest
      with_items:
        - epel-release
        - ansible
      when: ansible_distribution == "CentOS"
     
    - name: Add key for ansible from a ubuntu keyserver
      apt_key:
        keyserver: "{{ ubuntu_keyserver }}"
        id: "{{ ansible_key_id }}"
      when: ansible_distribution == "Debian"

    - name: Install ansible in debian based systems
      apt: 
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items: "{{ common_pkg }}"
      when: ansible_distribution == "Debian"
