---
- hosts: debian
  become: yes
  gather_facts: yes

  tasks:
    - name: Add key for ansible from a ubuntu keyserver
      apt_key:
        keyserver: "{{ ubuntu_keyserver }}"
        id: "{{ ansible_key_id }}"
      when: ansible_distribution == "Debian"

    - name: Installing the common packages on deb type systems
      apt: 
        name: "{{ item }}" 
        state: latest 
        update_cache: yes
      with_items: "{{ common_pkg }}"
      when: ansible_distribution == "Debian"
