---
- hosts: lxds
  gather_facts: no
  ignore_errors: yes

  tasks:
    - name: copy hosts as /etc/hosts in minions
      copy:
        src: hosts
        dest: /etc/hosts

- hosts: centos7
  gather_facts: no
  ignore_errors: yes

  tasks:
    - name: centos repo
      yum:
        name: https://repo.saltstack.com/yum/redhat/salt-repo-latest.el7.noarch.rpm
        state: latest

    - name: install salt-minion for centos
      yum:
        name: salt-minion
        state: latest
        update_cache: yes

    - name: Run the salt-minion service
      service:
        name: salt-minion
        enabled: true
        state: started

- hosts: ubuntu
  gather_facts: no
  ignore_errors: yes

  tasks:
    - name: Add salt key for Ubuntu
      apt_key:
        url: https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub
        state: present

    - name: Add salt repo for Ubuntu
      apt_repository:
        repo: deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main
        state: present
        filename: saltstack 

    - name: Install salt-minion in Ubuntu
      apt:
        name: salt-minion
        state: latest

    - name: Run the salt-minion service
      service:
        name: salt-minion
        enabled: true
        state: started
