---
- hosts: lxd
  gather_facts: yes
  ignore_errors: yes
  become: yes

  tasks:
    - name: copy hosts as /etc/hosts in minions
      copy:
        src: hosts
        dest: /etc/hosts

    - name: Install salt-minion packages in lxd minions
      yum:
        name: salt-minion
        state: present
      when: ansible_distribution == "CentOS"

    - name: Running salt-minion packages in lxd minions
      service:
        name: salt-minion
        enabled: true
        state: started
      when: ansible_distribution == "CentOS"

    - name: Install salt-minion packages in lxd minions
      yum:
        name: salt-minion
        state: present
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

    - name: Running salt-minion packages in lxd minions
      service:
        name: salt-minion
        enabled: true
        state: started
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
