---
rpm_package:
  - epel-release
  - git
  - ansible
  - vim
  - wget
  - iftop
  - htop
  - puppet
  - puppet-server
  - python-pip

salt_package:
  - salt-master
  - salt-ssh
  - salt-syndic
  - salt-cloud
  - salt-api

salt_minion_package:
  - salt-minion

deb_package:
  - git
  - ansible
  - vim
  - wget 
  - iftop
  - htop
